name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

# Permisos necesarios para el despliegue nativo de GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue activo a la vez
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      # Carga los archivos compilados como artefacto de GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Despliega el artefacto directamente en Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4